version: '3.1'
services:
  server:
    build: ./stats-service/
    image: stats_server
    container_name: stats-server
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/my_db
      - SPRING_DATASOURCE_USERNAME=myapp
      - SPRING_DATASOURCE_PASSWORD=myapp
      - SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: myapp
      POSTGRES_USER: myapp
      POSTGRES_DB: my_db
    ports:
      - "6432:5432"

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#    - "6060:6060"