version: '3.8'
services:
  server:
    build: ./stats-service/
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/my_db
      - SPRING_DATASOURCE_USERNAME=myapp
      - SPRING_DATASOURCE_PASSWORD=myapp
      - SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver

  db:
    image: postgres:13.7-alpine
    container_name: my_app-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=myapp
      - POSTGRES_USER=myapp
      - POSTGRES_DB=my_db
